easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Utilisateurs
        - App\Entity\Ordinateurs
        - App\Entity\Horaires
        - App\Entity\Attributions
